/**
 * Date: 12/12/20
 * Question Description
 You are given two strings s and t.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Return the letter that was added to t.



 Example 1:

 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 Example 2:

 Input: s = "", t = "y"
 Output: "y"
 Example 3:

 Input: s = "a", t = "aa"
 Output: "a"
 Example 4:

 Input: s = "ae", t = "aea"
 Output: "a"
 */

/**
 * Description: TODO
 * Time complexity:O(n);
 * Space complexity: O(1);

 */
public class _389_FindtheDifference {
    public char findTheDifference(String s, String t) {
        char last = t.charAt(t.length() - 1);
        for (int i = 0; i < s.length(); i++) {
            last ^= s.charAt(i);
            last ^= t.charAt(i);
        }
        return last;
    }
}
